### PR TITLE
Upgrade to latest version of heapless

### PR DESCRIPTION
**Pull request by hannobraun**

### CODE REVIEW

**Comment by jamesmunns** [comment]
Hey Hanno! No objections to this, though it would be a breaking change, so I'd probably want to hold off on a release to check if there are any other pending/desirable breaking changes that would make sense to roll in here.

Feel free to ping me (matrix preferred) in like a week if you haven't heard from me, and I'll cut a release then!

**Comment by hannobraun** [comment]
Sounds good!

**Comment by jamesmunns** [comment]
@hannobraun this has now been released as v0.7.0

**Comment by hannobraun** [comment]
Thank you, James!

**Pull request merged**
