### PR TITLE
Somethings odd with the import path

### PR DESCRIPTION
**Pull request by jamesmunns**
CC @Manishearth, I plan to do a release, but somethings funky with the `cargo package` and relative path imports to readmes.

I'll take a look at this in a bit.

### CODE REVIEW

**Comment by jamesmunns** [comment]
R-A and cargo package complain with either option:

```
error: couldn't read `src/../../../README.md`: No such file or directory (os error 2)
 --> src/lib.rs:3:33
  |
3 | #![cfg_attr(not(doctest), doc = include_str!("../../../README.md"))]
  |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)
help: there is a file with the same name in a different directory
  |
3 | #![cfg_attr(not(doctest), doc = include_str!("../../../../README.md"))]
  |                                              ~~~~~~~~~~~~~~~~~~~~~~~

error: could not compile `postcard` (lib) due to 1 previous error
error: failed to verify package tarball
```

**Comment by Manishearth** [comment]
Yeah in ICU4X we copy the license file around to avoid using relative paths like that. I forget if it was because it was broken-ish, or completely broken, but that might end up being the call. You can also check in a symlink into git (it'll become a regular file on publish, iirc)

**Comment by Manishearth** [comment]
(however git symlinks are weird on windows. i forgot in what way)

**Comment by robertbastian** [comment]
Windows needs admin privileges to create symlinks, so by default git creates a copy.

**Comment by jamesmunns** [comment]
Decided to just copy the file for now, to get this released.

**Pull request merged**
