### PR TITLE
Add function for computing the postcard serialized size of a value

### PR DESCRIPTION
**Pull request by lachlansneff-parallel**
This PR adds a function for computing the size of the postcard serialization of a value, as well as a ton of tests.

### CODE REVIEW

**Comment by ryankurte** [comment]
oooh this looks like it's on the way to #46?

boop @jamesmunns (plz forgive the boop-ing)

**Comment by jamesmunns** [comment]
@ryankurte booping always accepted/appreciated!

**Comment by jamesmunns** [comment]
Closing in favor of #66.

**Comment by ChocolateLoverRaj** [comment]
> Closing in favor of #66.

@jamesmunns it seems like you made a typo in what you are referencing since you referenced this closed PR. Btw I am seeing if there is a way of "serializing" just the length of the data without serializing the data itself. Rn I could to `to_allocvec` and get the size of that, but it seems like a waste.

**Comment by jamesmunns** [comment]
@ChocolateLoverRaj hmm, I'm not sure what PR I was looking for, but there is the `MaxSize` trait that you can use if your types are bounded. However, there is not a specific way to calculate the actual length without first serializing it if you have unbounded types, like `alloc/std::Vec` or `alloc/std::String` (as opposed to types like `heapless::Vec` or `heapless::String`, which have a specific upper limit).

Particularly with hand-implemented versions of the `Serialize` trait, it's difficult (or not possible) to tell what the actual serialized size is without actually exercising the serialize function.

One potential option that would still incur the same CPU effort but at least wouldn't allocate would be to implement a [serialization flavor](https://docs.rs/postcard/latest/postcard/ser_flavors/index.html) that just throws away the serialized data and just keeps a count of the bytes given to it.

**Pull request closed without merging**
